### ISSUE TITLE
中英文属性值问题。

### ISSUE THREAD

**Issue by jasonHzq** [nefe/one-cron#1]
目前 `lang` 在 `TS` 中可以由 <Cron lang={Language.English} /> 指定，但是在 `ES` 中，只能指定数字 `0` 或 `1`，比较奇怪。建议 `Enum` 指定值：

```typescript
export Enum Language {
  English = 'English',
  Chinese = 'Chinese',
}
```

这样 `TS` 的 `API` 和 `ES` 的 `API` 可以统一。

**Comment by PerkinJ** [comment]
目前统一为
`export Enum Language {
  English = 'English',
  Chinese = 'Chinese',
}`
lang属性目前只支持string类型，可选值为'Chinese' or 'English'
