### ISSUE TITLE
发布在 npm 上的包会导致 TS 报错

### ISSUE THREAD

**Issue by feichao93** [nefe/one-cron#13]
## 实际表现：

我已经将我自己项目中的 `skipLibCheck` 设置为  `true`，但 TS 仍然会针对 one-cron 进行报错。

报错如下图：

![image](https://user-images.githubusercontent.com/5550931/56095267-6b3ec480-5f0d-11e9-9fe4-00aef8624252.png)

## 期望表现：

TS 无报错

## 可能的修复方式

修改 tsconfig.json，生成 TS 类型声明文件（.d.ts），并将类型声明文件发布到 npm 上，然后将 package.json 中的 typings 指向类型声明文件。

![image](https://user-images.githubusercontent.com/5550931/56095288-b527aa80-5f0d-11e9-8f6a-9e54547c4f20.png)

**Comment by PerkinJ** [comment]
感谢，我们会抓紧时间修复！

**Comment by jasonHzq** [comment]
fixed

**Comment by jasonHzq** [comment]
star 都没有= =
