### ISSUE TITLE
增加对时间对可配置项

### ISSUE THREAD

**Issue by bnerDY** [nefe/one-cron#4]
对分钟，小时，有些场景可能用不到，所以开放更多api，让它可定制化

比如禁用分钟级别的timeperiod功能etc

**Comment by PerkinJ** [comment]
感谢提意见，后面我们会考虑增加这些功能，谢谢！

**Comment by PerkinJ** [comment]
> 对分钟，小时，有些场景可能用不到，所以开放更多api，让它可定制化
> 
> 比如禁用分钟级别的timeperiod功能etc

感谢提意见，后面我们会考虑增加这些功能，谢谢！

**Comment by jasonHzq** [comment]
> 对分钟，小时，有些场景可能用不到，所以开放更多api，让它可定制化
> 
> 比如禁用分钟级别的timeperiod功能etc

PR  welcome

**Comment by PerkinJ** [comment]
@bnerDY 0.2.16以上的版本已支持时间可配置
